added detect for vcredist_x64

diff --git a/run b/run
--- a/run
+++ b/run
@@ -18,14 +18,21 @@ hash erl 2>/dev/null
 if [ $? != 0 ]; then
   echo >&2 "erl not in PATH, try to find it"
   erl=$(echo $PWD/../erl*/)
-  echo "erl=$erl"
   if [ -f "$erl/bin/erl.exe" ]; then
-    echo "found $erl/bin/erl.exe"
     pwd=$PWD
     cd "$erl"
+    echo "found $erl/bin/erl.exe"
     ./Install.exe -s
-    cd "$pwd"
     export PATH="$erl/bin:$PATH"
+    erlc 2>/dev/null
+    if [ $? != 0 ]; then
+      echo >&2 "seems missing dependency, installing vcredist_x64"
+      ./vcredist_x64.exe
+      cd "$pwd"
+      $0 $@
+      exit $?
+    fi
+    cd "$pwd"
   else
     echo >&2 "erl runtime not found, exiting"
     exit 1
